"""Body/form creation — the mind spawns new torus instances and runnable form modules."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .engine import Engine, normalize
from .model import Hemisphere
from . import store
from .seed import seed_domain


FORM_TEMPLATE = '''"""Runnable body form generated by Beyond Binary Living Center.

Body: {name}
Domain: {domain}
Store: {store_path}
Specialty: {specialty_name}
"""

from __future__ import annotations

from pathlib import Path

from beyond_binary.center import LivingCenter
from beyond_binary.engine import Engine
from beyond_binary import store
from beyond_binary.model import Hemisphere

STORE = Path({store_path!r})
BODY_NAME = {name!r}
DOMAIN = {domain!r}
CAUSE_POLE = {cause_pole!r}
EFFECT_POLE = {effect_pole!r}
# Capabilities unique to this body (generated at embody — not parent cycle-only).
CAPABILITIES = [{specialty_name!r}]


def load_engine() -> Engine:
    return Engine(store.load(STORE))


def think(steps: int = 1) -> list[dict]:
    eng = load_engine()
    center = LivingCenter(eng, history=store.load_activity(STORE))
    center.mind_store = STORE
    reports = center.think(steps)
    store.save(eng.torus, STORE)
    store.append_activity([r.to_dict() for r in reports], STORE)
    return [r.to_dict() for r in reports]


def answer(topic: str) -> dict:
    eng = load_engine()
    dual = eng.answer(topic)
    return {{
        "topic": dual.topic,
        "cause_paths": dual.cause_paths,
        "effect_paths": dual.effect_paths,
        "between": dual.between,
        "note": dual.note,
        "body": BODY_NAME,
    }}


def {specialty_name}() -> dict:
    """Body-specific runnable capability derived from this body's poles.

    Not the generic think/answer cycle — measures this domain's dual structure.
    """
    eng = load_engine()
    cause = CAUSE_POLE
    effect = EFFECT_POLE
    if cause not in eng.torus.nodes or effect not in eng.torus.nodes:
        # Fall back to current roots if poles renamed/migrated.
        roots_c = [
            n.name
            for n in eng.torus.nodes.values()
            if n.parent is None and n.hemisphere is Hemisphere.CAUSE
        ]
        roots_e = [
            n.name
            for n in eng.torus.nodes.values()
            if n.parent is None and n.hemisphere is Hemisphere.EFFECT
        ]
        cause = roots_c[0] if roots_c else cause
        effect = roots_e[0] if roots_e else effect
    cause_children = [c.name for c in eng.children(cause)]
    effect_children = [c.name for c in eng.children(effect)]
    dual = eng.answer(cause)
    return {{
        "capability": {specialty_name!r},
        "body": BODY_NAME,
        "domain": DOMAIN,
        "cause_pole": cause,
        "effect_pole": effect,
        "cause_children": cause_children,
        "effect_children": effect_children,
        "cause_paths": dual.cause_paths,
        "effect_paths": dual.effect_paths,
        "gradient": len(cause_children) - len(effect_children),
    }}


if __name__ == "__main__":
    import json
    import sys

    eng = load_engine()
    print(json.dumps({{"body": BODY_NAME, "nodes": sorted(eng.torus.nodes), "capabilities": CAPABILITIES}}, indent=2))
    if len(sys.argv) > 1 and sys.argv[1] == "--specialty":
        print(json.dumps({specialty_name}(), indent=2))
    elif len(sys.argv) > 1:
        print(json.dumps(answer(sys.argv[1]), indent=2))
'''


def _safe_ident(*parts: str) -> str:
    raw = "_".join(parts)
    raw = re.sub(r"[^a-zA-Z0-9_]", "_", raw)
    raw = re.sub(r"_+", "_", raw).strip("_").lower()
    if not raw or raw[0].isdigit():
        raw = f"cap_{raw}"
    return raw[:48]


def specialty_for_engine(eng: Engine, body_name: str) -> tuple[str, str, str]:
    """Return (specialty_fn_name, cause_pole, effect_pole) for this body."""
    roots_c = [
        n
        for n in eng.torus.nodes.values()
        if n.parent is None and n.hemisphere is Hemisphere.CAUSE
    ]
    roots_e = [
        n
        for n in eng.torus.nodes.values()
        if n.parent is None and n.hemisphere is Hemisphere.EFFECT
    ]
    cause = roots_c[0].name if roots_c else "cause"
    effect = roots_e[0].name if roots_e else "effect"
    if roots_c and roots_c[0].opposite and eng.torus.nodes.get(roots_c[0].opposite):
        effect = eng.torus.nodes[roots_c[0].opposite].name
    fn = _safe_ident("pulse", cause, "to", effect, body_name)
    return fn, cause, effect


@dataclass
class BodyRecord:
    name: str
    store_path: str
    domain: str
    parent_instance: str
    created_from_cycle: int | None = None
    form_path: str | None = None
    parent_body: str | None = None  # lineage: body that invented/embodied this one
    specialty: str | None = None  # body-specific capability name

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "store_path": self.store_path,
            "domain": self.domain,
            "parent_instance": self.parent_instance,
            "created_from_cycle": self.created_from_cycle,
            "form_path": self.form_path,
            "parent_body": self.parent_body,
            "specialty": self.specialty,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BodyRecord":
        return cls(
            name=data["name"],
            store_path=data["store_path"],
            domain=data.get("domain", "thermal"),
            parent_instance=data.get("parent_instance", ""),
            created_from_cycle=data.get("created_from_cycle"),
            form_path=data.get("form_path"),
            parent_body=data.get("parent_body"),
            specialty=data.get("specialty"),
        )


@dataclass
class BodyRegistry:
    bodies: list[BodyRecord] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {"bodies": [b.to_dict() for b in self.bodies]}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BodyRegistry":
        return cls(bodies=[BodyRecord.from_dict(b) for b in data.get("bodies", [])])


def registry_path(mind_store: Path | str | None = None) -> Path:
    target = store.store_path(mind_store)
    return target.with_name(f"{target.stem}.bodies.json")


def load_registry(mind_store: Path | str | None = None) -> BodyRegistry:
    path = registry_path(mind_store)
    if not path.exists():
        return BodyRegistry()
    return BodyRegistry.from_dict(json.loads(path.read_text(encoding="utf-8")))


def save_registry(registry: BodyRegistry, mind_store: Path | str | None = None) -> Path:
    path = registry_path(mind_store)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(registry.to_dict(), indent=2, sort_keys=True) + "\n")
    return path


def write_form_module(
    record: BodyRecord,
    mind_store: Path | str | None = None,
    *,
    engine: Engine | None = None,
) -> Path:
    """Emit a runnable Python form with a body-specific specialty capability."""
    mind_path = store.store_path(mind_store)
    forms_dir = mind_path.parent / "forms"
    forms_dir.mkdir(parents=True, exist_ok=True)
    form_path = forms_dir / f"{record.name}.py"

    eng = engine
    if eng is None:
        eng = Engine(store.load(record.store_path))
    specialty_name, cause_pole, effect_pole = specialty_for_engine(eng, record.name)
    record.specialty = specialty_name

    form_path.write_text(
        FORM_TEMPLATE.format(
            name=record.name,
            domain=record.domain,
            store_path=record.store_path,
            specialty_name=specialty_name,
            cause_pole=cause_pole,
            effect_pole=effect_pole,
        ),
        encoding="utf-8",
    )
    return form_path


def load_form_specialty(record: BodyRecord):
    """Import the body form module and return (module, specialty_callable)."""
    import importlib.util

    if not record.form_path:
        raise FileNotFoundError("body has no form_path")
    path = Path(record.form_path)
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(
        f"beyond_binary_form_{record.name}", path
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load form {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    caps = list(getattr(mod, "CAPABILITIES", []) or [])
    if not caps:
        raise AttributeError("form exposes no CAPABILITIES")
    fn_name = caps[0]
    fn = getattr(mod, fn_name, None)
    if not callable(fn):
        raise AttributeError(f"specialty {fn_name!r} not callable")
    return mod, fn


def embody(
    mind: Engine,
    *,
    name: str,
    domain: str = "ontology",
    mind_store: Path | str | None = None,
    cycle: int | None = None,
) -> BodyRecord:
    """Spawn a new body: fresh domain torus + runnable form module."""
    mind_path = store.store_path(mind_store)
    body_path = mind_path.with_name(f"{mind_path.stem}.body.{name}.json")
    if body_path.exists():
        raise ValueError(f"body already exists: {body_path}")

    torus = seed_domain(domain)
    store.save(torus, body_path)
    store.clear_activity(body_path)

    body_eng = Engine(store.load(body_path))
    from .center import LivingCenter

    center = LivingCenter(body_eng)
    center.mind_store = body_path
    center.sync_cycle_index(store.load_activity(body_path))
    reports = center.think(3)
    store.save(body_eng.torus, body_path)
    store.append_activity([r.to_dict() for r in reports], body_path)

    record = BodyRecord(
        name=name,
        store_path=str(body_path),
        domain=domain,
        parent_instance=mind.torus.instance,
        created_from_cycle=cycle,
    )
    form_path = write_form_module(record, mind_path, engine=body_eng)
    record.form_path = str(form_path)

    registry = load_registry(mind_path)
    registry.bodies.append(record)
    save_registry(registry, mind_path)
    return record
