"""Body/form creation — mind spawns tori that run interpreted capability programs."""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from . import capability as capability_mod
from .engine import Engine
from .model import Hemisphere
from . import store
from .seed import seed_domain


# Forms share one entry point name; behavior comes from the persisted CapProgram.
SPECIALTY_ENTRY = "interpret_program"

FORM_TEMPLATE = '''"""Runnable body form generated by Beyond Binary Living Center.

Body: {name}
Domain: {domain}
Store: {store_path}
Capability program: {capability_path}
Entry: {specialty_name}
"""

from __future__ import annotations

from pathlib import Path

from beyond_binary.center import LivingCenter
from beyond_binary.engine import Engine
from beyond_binary import capability as capability_mod
from beyond_binary import store

STORE = Path({store_path!r})
BODY_NAME = {name!r}
DOMAIN = {domain!r}
CAPABILITY_PATH = Path({capability_path!r})
# Shared entry; per-body behavior is the CapProgram ops, not a pole-name template.
CAPABILITIES = [{specialty_name!r}]


def load_engine() -> Engine:
    return Engine(store.load(STORE))


def think(steps: int = 1) -> list[dict]:
    eng = load_engine()
    center = LivingCenter(eng, history=store.load_activity(STORE))
    center.mind_store = STORE
    reports = center.think(steps)
    store.save(eng.torus, STORE)
    store.append_activity([r.to_dict() for r in reports], STORE)
    # Structural pressure can grow the capability program.
    program = capability_mod.load_program(STORE)
    program = capability_mod.evolve_program(program, eng)
    capability_mod.save_program(program, STORE)
    return [r.to_dict() for r in reports]


def answer(topic: str) -> dict:
    eng = load_engine()
    dual = eng.answer(topic)
    return {{
        "topic": dual.topic,
        "cause_paths": dual.cause_paths,
        "effect_paths": dual.effect_paths,
        "between": dual.between,
        "note": dual.note,
        "body": BODY_NAME,
    }}


def {specialty_name}() -> dict:
    """Run this body's persisted capability program (interpreted ops, not a template)."""
    eng = load_engine()
    program = capability_mod.load_program(STORE)
    program = capability_mod.evolve_program(program, eng)
    capability_mod.save_program(program, STORE)
    out = capability_mod.interpret(program, eng)
    out["domain"] = DOMAIN
    out["body"] = BODY_NAME
    return out


if __name__ == "__main__":
    import json
    import sys

    eng = load_engine()
    program = capability_mod.load_program(STORE)
    print(
        json.dumps(
            {{
                "body": BODY_NAME,
                "nodes": sorted(eng.torus.nodes),
                "capabilities": CAPABILITIES,
                "program_id": program.program_id,
                "ops": [o.get("op") for o in program.ops],
                "revisions": program.revisions,
            }},
            indent=2,
        )
    )
    if len(sys.argv) > 1 and sys.argv[1] == "--specialty":
        print(json.dumps({specialty_name}(), indent=2))
    elif len(sys.argv) > 1:
        print(json.dumps(answer(sys.argv[1]), indent=2))
'''


def _safe_ident(*parts: str) -> str:
    raw = "_".join(parts)
    raw = re.sub(r"[^a-zA-Z0-9_]", "_", raw)
    raw = re.sub(r"_+", "_", raw).strip("_").lower()
    if not raw or raw[0].isdigit():
        raw = f"cap_{raw}"
    return raw[:48]


def specialty_for_engine(eng: Engine, body_name: str) -> tuple[str, str, str]:
    """Return (specialty_fn_name, cause_pole, effect_pole).

    Specialty entry is always interpret_program; poles are informational only.
    """
    roots_c = [
        n
        for n in eng.torus.nodes.values()
        if n.parent is None and n.hemisphere is Hemisphere.CAUSE
    ]
    roots_e = [
        n
        for n in eng.torus.nodes.values()
        if n.parent is None and n.hemisphere is Hemisphere.EFFECT
    ]
    cause = roots_c[0].name if roots_c else "cause"
    effect = roots_e[0].name if roots_e else "effect"
    if roots_c and roots_c[0].opposite and eng.torus.nodes.get(roots_c[0].opposite):
        effect = eng.torus.nodes[roots_c[0].opposite].name
    return SPECIALTY_ENTRY, cause, effect


@dataclass
class BodyRecord:
    name: str
    store_path: str
    domain: str
    parent_instance: str
    created_from_cycle: int | None = None
    form_path: str | None = None
    parent_body: str | None = None  # lineage: body that invented/embodied this one
    specialty: str | None = None  # entry point (interpret_program)
    capability_path: str | None = None  # persisted CapProgram JSON

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "store_path": self.store_path,
            "domain": self.domain,
            "parent_instance": self.parent_instance,
            "created_from_cycle": self.created_from_cycle,
            "form_path": self.form_path,
            "parent_body": self.parent_body,
            "specialty": self.specialty,
            "capability_path": self.capability_path,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BodyRecord":
        return cls(
            name=data["name"],
            store_path=data["store_path"],
            domain=data.get("domain", "thermal"),
            parent_instance=data.get("parent_instance", ""),
            created_from_cycle=data.get("created_from_cycle"),
            form_path=data.get("form_path"),
            parent_body=data.get("parent_body"),
            specialty=data.get("specialty"),
            capability_path=data.get("capability_path"),
        )


@dataclass
class BodyRegistry:
    bodies: list[BodyRecord] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {"bodies": [b.to_dict() for b in self.bodies]}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BodyRegistry":
        return cls(bodies=[BodyRecord.from_dict(b) for b in data.get("bodies", [])])


def registry_path(mind_store: Path | str | None = None) -> Path:
    target = store.store_path(mind_store)
    return target.with_name(f"{target.stem}.bodies.json")


def load_registry(mind_store: Path | str | None = None) -> BodyRegistry:
    path = registry_path(mind_store)
    if not path.exists():
        return BodyRegistry()
    return BodyRegistry.from_dict(json.loads(path.read_text(encoding="utf-8")))


def save_registry(registry: BodyRegistry, mind_store: Path | str | None = None) -> Path:
    path = registry_path(mind_store)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(registry.to_dict(), indent=2, sort_keys=True) + "\n")
    return path


def write_form_module(
    record: BodyRecord,
    mind_store: Path | str | None = None,
    *,
    engine: Engine | None = None,
    invent_edit: dict[str, Any] | None = None,
) -> Path:
    """Emit a runnable form that interprets a per-body CapProgram."""
    mind_path = store.store_path(mind_store)
    forms_dir = mind_path.parent / "forms"
    forms_dir.mkdir(parents=True, exist_ok=True)
    form_path = forms_dir / f"{record.name}.py"

    eng = engine
    if eng is None:
        eng = Engine(store.load(record.store_path))
    specialty_name, _cause_pole, _effect_pole = specialty_for_engine(eng, record.name)
    record.specialty = specialty_name

    # Persist an initial capability program derived from live structure.
    # Search invent edit_ast couples distinct prim_* into the CapProgram (G11).
    program = capability_mod.initial_program_for(eng, record.name)
    program = capability_mod.evolve_program(program, eng)
    if invent_edit:
        program = capability_mod.couple_program_to_invent_edit(
            program, eng, invent_edit
        )
    cap_path = capability_mod.save_program(program, record.store_path)
    record.capability_path = str(cap_path)

    form_path.write_text(
        FORM_TEMPLATE.format(
            name=record.name,
            domain=record.domain,
            store_path=record.store_path,
            specialty_name=specialty_name,
            capability_path=str(cap_path),
        ),
        encoding="utf-8",
    )
    return form_path


def load_form_specialty(record: BodyRecord):
    """Import the body form module and return (module, specialty_callable)."""
    import importlib.util

    if not record.form_path:
        raise FileNotFoundError("body has no form_path")
    path = Path(record.form_path)
    if not path.exists():
        raise FileNotFoundError(path)
    spec = importlib.util.spec_from_file_location(
        f"beyond_binary_form_{record.name}", path
    )
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load form {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    caps = list(getattr(mod, "CAPABILITIES", []) or [])
    if not caps:
        raise AttributeError("form exposes no CAPABILITIES")
    fn_name = caps[0]
    fn = getattr(mod, fn_name, None)
    if not callable(fn):
        raise AttributeError(f"specialty {fn_name!r} not callable")
    return mod, fn


def embody(
    mind: Engine,
    *,
    name: str,
    domain: str = "ontology",
    mind_store: Path | str | None = None,
    cycle: int | None = None,
) -> BodyRecord:
    """Spawn a new body: fresh domain torus + CapProgram + runnable form."""
    mind_path = store.store_path(mind_store)
    body_path = mind_path.with_name(f"{mind_path.stem}.body.{name}.json")
    if body_path.exists():
        raise ValueError(f"body already exists: {body_path}")

    torus = seed_domain(domain)
    store.save(torus, body_path)
    store.clear_activity(body_path)

    body_eng = Engine(store.load(body_path))
    from .center import LivingCenter

    center = LivingCenter(body_eng)
    center.mind_store = body_path
    center.sync_cycle_index(store.load_activity(body_path))
    # Embody warm-up is not the primary invent path (#2).
    reports = center.think(3, allow_primary_invent=False)
    store.save(body_eng.torus, body_path)
    store.append_activity([r.to_dict() for r in reports], body_path)

    record = BodyRecord(
        name=name,
        store_path=str(body_path),
        domain=domain,
        parent_instance=mind.torus.instance,
        created_from_cycle=cycle,
    )
    form_path = write_form_module(record, mind_path, engine=body_eng)
    record.form_path = str(form_path)

    registry = load_registry(mind_path)
    registry.bodies.append(record)
    save_registry(registry, mind_path)
    return record
