"""Body/form creation — the mind spawns new torus instances and runnable form modules."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .engine import Engine
from . import store
from .seed import seed_domain


FORM_TEMPLATE = '''"""Runnable body form generated by Beyond Binary Living Center.

Body: {name}
Domain: {domain}
Store: {store_path}
"""

from __future__ import annotations

from pathlib import Path

from beyond_binary.center import LivingCenter
from beyond_binary.engine import Engine
from beyond_binary import store

STORE = Path({store_path!r})


def load_engine() -> Engine:
    return Engine(store.load(STORE))


def think(steps: int = 1) -> list[dict]:
    eng = load_engine()
    center = LivingCenter(eng, history=store.load_activity(STORE))
    center.mind_store = STORE
    reports = center.think(steps)
    store.save(eng.torus, STORE)
    store.append_activity([r.to_dict() for r in reports], STORE)
    return [r.to_dict() for r in reports]


def answer(topic: str) -> dict:
    eng = load_engine()
    dual = eng.answer(topic)
    return {{
        "topic": dual.topic,
        "cause_paths": dual.cause_paths,
        "effect_paths": dual.effect_paths,
        "between": dual.between,
        "note": dual.note,
        "body": {name!r},
    }}


if __name__ == "__main__":
    import json
    import sys

    eng = load_engine()
    print(json.dumps({{"body": {name!r}, "nodes": sorted(eng.torus.nodes)}}, indent=2))
    if len(sys.argv) > 1:
        print(json.dumps(answer(sys.argv[1]), indent=2))
'''


@dataclass
class BodyRecord:
    name: str
    store_path: str
    domain: str
    parent_instance: str
    created_from_cycle: int | None = None
    form_path: str | None = None
    parent_body: str | None = None  # lineage: body that invented/embodied this one

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "store_path": self.store_path,
            "domain": self.domain,
            "parent_instance": self.parent_instance,
            "created_from_cycle": self.created_from_cycle,
            "form_path": self.form_path,
            "parent_body": self.parent_body,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BodyRecord":
        return cls(
            name=data["name"],
            store_path=data["store_path"],
            domain=data.get("domain", "thermal"),
            parent_instance=data.get("parent_instance", ""),
            created_from_cycle=data.get("created_from_cycle"),
            form_path=data.get("form_path"),
            parent_body=data.get("parent_body"),
        )


@dataclass
class BodyRegistry:
    bodies: list[BodyRecord] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {"bodies": [b.to_dict() for b in self.bodies]}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "BodyRegistry":
        return cls(bodies=[BodyRecord.from_dict(b) for b in data.get("bodies", [])])


def registry_path(mind_store: Path | str | None = None) -> Path:
    target = store.store_path(mind_store)
    return target.with_name(f"{target.stem}.bodies.json")


def load_registry(mind_store: Path | str | None = None) -> BodyRegistry:
    path = registry_path(mind_store)
    if not path.exists():
        return BodyRegistry()
    return BodyRegistry.from_dict(json.loads(path.read_text(encoding="utf-8")))


def save_registry(registry: BodyRegistry, mind_store: Path | str | None = None) -> Path:
    path = registry_path(mind_store)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(registry.to_dict(), indent=2, sort_keys=True) + "\n")
    return path


def write_form_module(record: BodyRecord, mind_store: Path | str | None = None) -> Path:
    """Emit a runnable Python form module beside the mind store."""
    mind_path = store.store_path(mind_store)
    forms_dir = mind_path.parent / "forms"
    forms_dir.mkdir(parents=True, exist_ok=True)
    form_path = forms_dir / f"{record.name}.py"
    form_path.write_text(
        FORM_TEMPLATE.format(
            name=record.name,
            domain=record.domain,
            store_path=record.store_path,
        ),
        encoding="utf-8",
    )
    return form_path


def embody(
    mind: Engine,
    *,
    name: str,
    domain: str = "ontology",
    mind_store: Path | str | None = None,
    cycle: int | None = None,
) -> BodyRecord:
    """Spawn a new body: fresh domain torus + runnable form module."""
    mind_path = store.store_path(mind_store)
    body_path = mind_path.with_name(f"{mind_path.stem}.body.{name}.json")
    if body_path.exists():
        raise ValueError(f"body already exists: {body_path}")

    torus = seed_domain(domain)
    store.save(torus, body_path)
    store.clear_activity(body_path)

    body_eng = Engine(store.load(body_path))
    from .center import LivingCenter

    center = LivingCenter(body_eng)
    center.mind_store = body_path
    center.sync_cycle_index(store.load_activity(body_path))
    reports = center.think(3)
    store.save(body_eng.torus, body_path)
    store.append_activity([r.to_dict() for r in reports], body_path)

    record = BodyRecord(
        name=name,
        store_path=str(body_path),
        domain=domain,
        parent_instance=mind.torus.instance,
        created_from_cycle=cycle,
    )
    form_path = write_form_module(record, mind_path)
    record.form_path = str(form_path)

    registry = load_registry(mind_path)
    registry.bodies.append(record)
    save_registry(registry, mind_path)
    return record
